<?php
$reportLanguage = [
    'en' => [
        ':language'    => 'English',
        'Account'      => 'Account',
        'Basic'        => 'Basic',
        'Begin'        => 'Begin',
        'Cars'         => 'Cars',
        'Comparison'   => 'Comparison',
        'Current'      => 'Current',
        'Description'  => 'Description',
        'Diff'         => 'Diff',
        'DiffPlan'     => 'Diff Plan %',
        'Forecast'     => 'Forecast',
        'Gas'          => 'Gas',
        'History'      => 'History',
        'ID'           => 'ID',
        'Leasing'      => 'Leasing',
        'LeasingBegin' => 'LeasingBegin',
        'LeasingEnd'   => 'LeasingEnd',
        'Misc'         => 'Misc',
        'Overview'     => 'Overview',
        'Owner'        => 'Owner',
        'Plan'         => 'Plan',
        'Planning'     => 'Planning',
        'Progress'     => 'Progress',
        'Rep./Insp.'   => 'Rep./Insp.',
        'Rent'         => 'Rent',
        'Sold'         => 'Sold',
        'Sum'          => 'Sum',
        'Tax'          => 'Tax',
        'Wheels'       => 'Wheels',
    ]
];